[tool.poetry]
name = "uceasy"
version = "0.2.0-a0"
description = "Wrapper for the Phyluce phylogenomics software package"
authors = ["Caio Raposo <caioraposo@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://uceasy.github.io"
repository = "https://github.com/uceasy/uceasy"
keywords = ["uce", "phyluce", "ultraconserved elements"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-mock = "^1.10"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
pre-commit = "^1.18"
nox = "^2019.11.9"
flake8 = "^3.7.9"
coverage = {extras = ["toml"], version = "^5.0.4"}
pytest-cov = "^2.8.1"
codecov = "^2.0.16"

[tool.poetry.scripts]
uceasy = "uceasy.console:cli"

[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["uceasy"]

[tool.coverage.report]
show_missing = true
fail_under = 20

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

