[tool.poetry]
name = "uceasy"
version = "0.1.0"
description = "Wrapper for the Phyluce phylogenomics software package"
authors = ["Caio Raposo <caioraposo@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.0"
flask = "^1.1"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
jedi = "^0.14.1"
pylint = "^2.3"
pytest-mock = "^1.10"

[tool.poetry.scripts]
uceasy = "cli.uceast_cli:uceasy"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

